{
 "title": "aiDAPTIV Log Storage",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Service",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: \"phisonai\",\r\n    tag: \"serviceId\",\r\n    predicate: (r) => r._measurement == \"n_log\",\r\n    start: v.timeRangeStart,\r\n    stop:v.timeRangeStop\r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Count Record",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"n_log\" and r[\"flowId\"] != \"\")\r\n  |> filter(fn: (r) => r.serviceId =~ /^${Service:regex}$/)\r\n  |> group(columns: [\"flowId\"], mode: \"by\")\r\n  |> unique(column:\"flowId\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n  |> cumulativeSum(columns: [\"_value\"]) \r\n  |> aggregateWindow(every: 20m, fn: count)"
    }
   ]
  },
  {
   "title": "User Count Record",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"n_log\" and r[\"userId\"] != \"\")   \r\n  |> filter(fn: (r) => r.serviceId =~ /^${Service:regex}$/)\r\n  |> group(columns: [\"userId\"], mode: \"by\")\r\n  |> unique(column:\"userId\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n  |> cumulativeSum(columns: [\"_value\"]) \r\n  |> aggregateWindow(every: 20m, fn: count)"
    }
   ]
  },
  {
   "title": "aiDAPTIV Log Record",
   "type": "table",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"n_log\")\r\n  |> filter(fn: (r) => r.serviceId =~ /^${Service:regex}$/)\r\n  |> keep(columns: [\"_time\", \"level\",\"errorCode\",\"version\", \"_value\", \"callSite\",\"serviceId\",\"ip\",\"flowId\",\"userId\"])\r\n|> group()"
    }
   ]
  }
 ]
}